//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/AirplanePhysics/Code/Scripts/Input/AirplaneInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @AirplaneInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @AirplaneInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AirplaneInputActions"",
    ""maps"": [
        {
            ""name"": ""AirplaneControls"",
            ""id"": ""79725fb6-8b7e-4dab-9ef6-eb5482ce3acf"",
            ""actions"": [
                {
                    ""name"": ""Pitch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2ffb7d96-f2eb-4e04-96da-7d3cfaf5380a"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c5e47905-5202-42d6-b65e-ad8e4199a900"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Yaw"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b3a47911-cd1a-42ed-95db-b791c05145f7"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b375e5ad-7fe3-44ae-9766-7a805a3c2ca3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""45f11c58-4093-47b1-af9f-08ac2caa5d28"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlapsUP"",
                    ""type"": ""Button"",
                    ""id"": ""77d9e6ab-9160-4409-8bcd-03982ca9df48"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FlapsDOWN"",
                    ""type"": ""Button"",
                    ""id"": ""51667615-5b2c-4031-a46f-8ecd7b22ea45"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8cea008a-4230-4270-90fd-d0b92c55e854"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfdee0e3-e289-4635-9b32-006d982b215c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7f395e02-3d69-4b36-9e30-58f28ec93bbb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bf00e9dd-7147-4b44-9a4a-764ecff0322f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""950d8031-7673-4c5e-b2bc-76597df548bd"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""dcf64077-a294-4c52-bb0a-11394c46b167"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4d11e9ac-803c-42f9-a585-c8355936d6b9"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ba09ac1a-d9c4-45fb-89d0-43889f08bdaa"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""6abb3229-a3d2-430d-b4a0-a5bb9da7707d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""6be4279c-7fe6-4e60-8d0b-bbe7b366fc4a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0b1b3bb9-d720-4025-84b9-56542c715477"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ceae0a24-51a9-4d00-ae55-8288e5dfe9d7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""506c6f72-8fbc-488b-9321-3a9b0f0beb47"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""268db39d-9aa3-42f8-9947-7c957256b509"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""030684af-0a9b-4455-ae08-22d31d5a0c49"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ac85502e-343e-4ae1-832f-1bccb0c29922"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""95461112-6d16-44b4-8753-82935fcd2433"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9e843e4d-6862-4c4b-8107-c09a2448eeda"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""ace9ed58-5617-472a-8ca3-7e3e9f5b1043"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e61126de-dbcb-4b57-873d-429f5f9be187"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""88848584-2837-4f52-81cb-900db20b2748"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dc4441f9-e2de-4953-aaa3-cc4b7ef42ee9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3594bac0-4c3e-477e-96bb-4ee8926c5ffe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""b32f4540-ce5b-4636-a4f2-c802ac572a25"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""15c56005-db82-434b-ba5a-7680904df5af"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""5c4b2737-4cc9-4e1b-987d-6d1e892f6790"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2ff5daee-b746-4c51-ab93-88eeb4e39eef"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""FlapsUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba3d1b76-5bdc-4471-8bdc-5634045c63ec"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlapsUP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57bbd782-664e-4768-ab0b-1bdf64423d5a"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Airplane_Keyboard"",
                    ""action"": ""FlapsDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8da6c1ed-3154-4947-9cc6-74b110ac6c50"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FlapsDOWN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Airplane_Keyboard"",
            ""bindingGroup"": ""Airplane_Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Airplane_PS4"",
            ""bindingGroup"": ""Airplane_PS4"",
            ""devices"": [
                {
                    ""devicePath"": ""<DualShockGamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // AirplaneControls
        m_AirplaneControls = asset.FindActionMap("AirplaneControls", throwIfNotFound: true);
        m_AirplaneControls_Pitch = m_AirplaneControls.FindAction("Pitch", throwIfNotFound: true);
        m_AirplaneControls_Roll = m_AirplaneControls.FindAction("Roll", throwIfNotFound: true);
        m_AirplaneControls_Yaw = m_AirplaneControls.FindAction("Yaw", throwIfNotFound: true);
        m_AirplaneControls_Throttle = m_AirplaneControls.FindAction("Throttle", throwIfNotFound: true);
        m_AirplaneControls_Brake = m_AirplaneControls.FindAction("Brake", throwIfNotFound: true);
        m_AirplaneControls_FlapsUP = m_AirplaneControls.FindAction("FlapsUP", throwIfNotFound: true);
        m_AirplaneControls_FlapsDOWN = m_AirplaneControls.FindAction("FlapsDOWN", throwIfNotFound: true);
    }

    ~@AirplaneInputActions()
    {
        UnityEngine.Debug.Assert(!m_AirplaneControls.enabled, "This will cause a leak and performance issues, AirplaneInputActions.AirplaneControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // AirplaneControls
    private readonly InputActionMap m_AirplaneControls;
    private List<IAirplaneControlsActions> m_AirplaneControlsActionsCallbackInterfaces = new List<IAirplaneControlsActions>();
    private readonly InputAction m_AirplaneControls_Pitch;
    private readonly InputAction m_AirplaneControls_Roll;
    private readonly InputAction m_AirplaneControls_Yaw;
    private readonly InputAction m_AirplaneControls_Throttle;
    private readonly InputAction m_AirplaneControls_Brake;
    private readonly InputAction m_AirplaneControls_FlapsUP;
    private readonly InputAction m_AirplaneControls_FlapsDOWN;
    public struct AirplaneControlsActions
    {
        private @AirplaneInputActions m_Wrapper;
        public AirplaneControlsActions(@AirplaneInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pitch => m_Wrapper.m_AirplaneControls_Pitch;
        public InputAction @Roll => m_Wrapper.m_AirplaneControls_Roll;
        public InputAction @Yaw => m_Wrapper.m_AirplaneControls_Yaw;
        public InputAction @Throttle => m_Wrapper.m_AirplaneControls_Throttle;
        public InputAction @Brake => m_Wrapper.m_AirplaneControls_Brake;
        public InputAction @FlapsUP => m_Wrapper.m_AirplaneControls_FlapsUP;
        public InputAction @FlapsDOWN => m_Wrapper.m_AirplaneControls_FlapsDOWN;
        public InputActionMap Get() { return m_Wrapper.m_AirplaneControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AirplaneControlsActions set) { return set.Get(); }
        public void AddCallbacks(IAirplaneControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_AirplaneControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_AirplaneControlsActionsCallbackInterfaces.Add(instance);
            @Pitch.started += instance.OnPitch;
            @Pitch.performed += instance.OnPitch;
            @Pitch.canceled += instance.OnPitch;
            @Roll.started += instance.OnRoll;
            @Roll.performed += instance.OnRoll;
            @Roll.canceled += instance.OnRoll;
            @Yaw.started += instance.OnYaw;
            @Yaw.performed += instance.OnYaw;
            @Yaw.canceled += instance.OnYaw;
            @Throttle.started += instance.OnThrottle;
            @Throttle.performed += instance.OnThrottle;
            @Throttle.canceled += instance.OnThrottle;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @FlapsUP.started += instance.OnFlapsUP;
            @FlapsUP.performed += instance.OnFlapsUP;
            @FlapsUP.canceled += instance.OnFlapsUP;
            @FlapsDOWN.started += instance.OnFlapsDOWN;
            @FlapsDOWN.performed += instance.OnFlapsDOWN;
            @FlapsDOWN.canceled += instance.OnFlapsDOWN;
        }

        private void UnregisterCallbacks(IAirplaneControlsActions instance)
        {
            @Pitch.started -= instance.OnPitch;
            @Pitch.performed -= instance.OnPitch;
            @Pitch.canceled -= instance.OnPitch;
            @Roll.started -= instance.OnRoll;
            @Roll.performed -= instance.OnRoll;
            @Roll.canceled -= instance.OnRoll;
            @Yaw.started -= instance.OnYaw;
            @Yaw.performed -= instance.OnYaw;
            @Yaw.canceled -= instance.OnYaw;
            @Throttle.started -= instance.OnThrottle;
            @Throttle.performed -= instance.OnThrottle;
            @Throttle.canceled -= instance.OnThrottle;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @FlapsUP.started -= instance.OnFlapsUP;
            @FlapsUP.performed -= instance.OnFlapsUP;
            @FlapsUP.canceled -= instance.OnFlapsUP;
            @FlapsDOWN.started -= instance.OnFlapsDOWN;
            @FlapsDOWN.performed -= instance.OnFlapsDOWN;
            @FlapsDOWN.canceled -= instance.OnFlapsDOWN;
        }

        public void RemoveCallbacks(IAirplaneControlsActions instance)
        {
            if (m_Wrapper.m_AirplaneControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IAirplaneControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_AirplaneControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_AirplaneControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public AirplaneControlsActions @AirplaneControls => new AirplaneControlsActions(this);
    private int m_Airplane_KeyboardSchemeIndex = -1;
    public InputControlScheme Airplane_KeyboardScheme
    {
        get
        {
            if (m_Airplane_KeyboardSchemeIndex == -1) m_Airplane_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Airplane_Keyboard");
            return asset.controlSchemes[m_Airplane_KeyboardSchemeIndex];
        }
    }
    private int m_Airplane_PS4SchemeIndex = -1;
    public InputControlScheme Airplane_PS4Scheme
    {
        get
        {
            if (m_Airplane_PS4SchemeIndex == -1) m_Airplane_PS4SchemeIndex = asset.FindControlSchemeIndex("Airplane_PS4");
            return asset.controlSchemes[m_Airplane_PS4SchemeIndex];
        }
    }
    public interface IAirplaneControlsActions
    {
        void OnPitch(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnYaw(InputAction.CallbackContext context);
        void OnThrottle(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnFlapsUP(InputAction.CallbackContext context);
        void OnFlapsDOWN(InputAction.CallbackContext context);
    }
}
